spring:
  application:
    name: Carro
  datasource:
    url: jdbc:h2:mem:meubanco
    driver-class-name: org.h2.Driver
    username: Andrew
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

